apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-az-overlays-computeimagegallery
  description: Terraform overlay module for Azure Compute Image Gallery
  annotations:
    github.com/project-slug: POps-Rox/tf-az-overlays-computeimagegallery
    backstage.io/techdocs-ref: dir:.
  tags:
    - terraform
    - terraform-module
    - azure
    - platform-ops
  links:
    - url: https://github.com/POps-Rox/tf-az-overlays-computeimagegallery
      title: GitHub Repository
      icon: github
spec:
  type: terraform-module
  owner: platform-ops-team
  lifecycle: production
  system: pops-rox-platform
